---
Name: phonelink
After:
  - '#cmsmodals'
---
SilverStripe\Admin\ModalController:
  extensions:
    - Firebrand\PhoneLink\Forms\PhoneLinkModalExtension
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Firebrand\PhoneLink\Extensions\LeftAndMainExtension