---
Name: prductlinkmodule
After:
  - '#cmsmodals'
---
SilverStripe\Admin\ModalController:
  extensions:
    - VinceCabrera\ProductLink\Forms\ProductLinkModalExtension
SilverStripe\Admin\LeftAndMain:
  extensions:
    - VinceCabrera\ProductLink\Extensions\LeftAndMainExtension
